name: interchange-regression-testing-latest

channels:
  - conda-forge/label/openff-toolkit_rc
  - conda-forge/label/openff-interchange_rc
  - conda-forge
  - openeye

dependencies:
    # Core
  - python =3.10
  - pip

  - click
  - rich

  - pydantic =2
  - numpy
  - pyyaml

  - openmm
  - openeye-toolkits

  - deepdiff
  - xmltodict

  - openff-toolkit >=0.11.0
  - openff-interchange >=0.3.29
