name: interchange-regression-testing

channels:
  - conda-forge/label/openff-toolkit_rc
  - conda-forge/label/openff-interchange_rc
  - conda-forge
  - openeye

dependencies:
    # Core
  - python =3.9
  - pip

  - click
  - rich

  - pydantic
  - numpy
  - pyyaml

  - openmm
  - openeye-toolkits

  - deepdiff
  - xmltodict

  - openff-toolkit >=0.11.0rc3
